"""create jobs table

Revision ID: dba8801af156
Revises: f2174feba7e3
Create Date: 2026-06-11 20:29:00.774408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba8801af156'
down_revision: Union[str, Sequence[str], None] = 'f2174feba7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "jobs",

    sa.Column("id", sa.Integer(), nullable=False),

    sa.Column(
        "recruiter_id",
        sa.Integer(),
        nullable=False
    ),

    sa.Column(
        "title",
        sa.String(length=255),
        nullable=False
    ),

    sa.Column(
        "description",
        sa.Text(),
        nullable=False
    ),

    sa.Column(
        "created_at",
        sa.DateTime(),
        nullable=True
    ),

    sa.ForeignKeyConstraint(
        ["recruiter_id"],
        ["users.id"],
        ondelete="CASCADE"
    ),

    sa.PrimaryKeyConstraint("id")
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
