"""create resume_skills table

Revision ID: f2174feba7e3
Revises: 47a52ba97316
Create Date: 2026-06-11 20:18:21.178463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2174feba7e3'
down_revision: Union[str, Sequence[str], None] = '47a52ba97316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'resume_skills',

        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),

        sa.ForeignKeyConstraint(
            ['resume_id'],
            ['resumes.id'],
            ondelete='CASCADE'
        ),

        sa.ForeignKeyConstraint(
            ['skill_id'],
            ['skills.id'],
            ondelete='CASCADE'
        ),

        sa.PrimaryKeyConstraint(
            'resume_id',
            'skill_id'
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_skills')
    # ### end Alembic commands ###
